#!/bin/sh

case $BLOCK_BUTTON in
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

threshold=5
load=$(cut -d ' ' -f1 /proc/loadavg)

if [ 1 -eq $(echo "$load > $threshold" | bc) ]; then
	color=1
fi
echo " $load%" $color
