#!/bin/sh

case $BLOCK_BUTTON in
	1) setsid -f "$TERMINAL" -e pulsemixer ;;
	2) pamixer -t ;;
	4) pamixer --allow-boost -i 1 ;;
	5) pamixer --allow-boost -d 1 ;;
	3) notify-send "📢 Volume module" "\- Shows volume 🔊, 🔇 if muted.
- Middle click to mute.
- Scroll to change." ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

if [ "$(pamixer --get-mute)" = true ]; then
	echo " " 1
	exit
fi

vol="$(pamixer --get-volume)"
[ $? -ne 0 ] && [ -z "$vol" ] && exit 1

if [ "$vol" -gt 40 ]; then
	icon=" "
elif [ "$vol" -gt 15 ]; then
	icon=" "
else
	icon=" "
fi

echo "^c#D3869B^$icon^d^$vol%"
