#!/bin/sh

# A dwm_bar function to print the weather from wttr.in
# Joe Standring <git@joestandring.com>
# GNU GPLv3

# Dependencies: curl

# Change the value of LOCATION to match your city
dwm_weather() {
    LOCATION=Berlin

    DATA=$(curl -s wttr/$LOCATION?format=1)
    echo "$DATA"
}

dwm_weather
